services:
  db:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  provider:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    command:
      - --WORKERS_NUM=${WORKERS_NUM}
      - --NODE=${NODE}
      - --CONNECTION=${CONNECTION}
      - --AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - --AWS_SECURITY_KEY=${AWS_SECURITY_KEY}
      - --S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - --S3_FILE_KEY=${S3_FILE_KEY}
      - --MODE=${MODE}

volumes:
  postgres_data:

